version: '3.9'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo_db
      PGDATA: /data/postgres_todo_dev
    ports:
      - "5432:5432"
